sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: M/zUDW9uhxjQf0tLZjxmVZRe3a1Tt+3ggy677OF/ERmRM85txisUbdjcJSrJlhJDClUoZ+ADcyOAnVjFEyITiINga9QfymZ+PoJM0yK/2QzbPY5OAyhhSP6RjSsK3SgtOVptQxkeTeYNlopcpDj3eAZi7yDJHnsHpp/uOnEynIOrHOzneO8CX4dxc7keGFHp8n8I1c1v6Q0n8+tRaf7CEysR0Zk//pYtgopxfioujvw8wyd9JlTZedLULxgtkuGIKWl+3HANfDUrvgH8by70p+NoNEtnLf/HzbSkTpy1ZyoVuisWyPSHe5rcBDSICVGzILFVG1TfzvD40zkvQBtIZ4EfPXXB214AEHgkeGyReVL6/zWT8E7+iEvN8BTSNFuKYk0JB2e0QkOFNT1LSMfG5U2HJ6HXkLLzf8jWjaon1hsNQQ6JvPQjIbptGgx3DaHcDMPN8Md6dCm4jLfxCaVaKQRq+qLhb1jI+dczWINM5lF5YGH8bIuxFqkdF5MSORvY+qWckfVuRe/sCWMG9/gs09l+oSwCNzewb8/1dRkY2w3saowUkSTot/4fU/pTqXIhWfyQU7FPG7DLFSZQcOB0MOHcNmYkpLjZrNzrBm/kTeVNNZc3o6cPz0Nfti4/XF7PFIYHW4AIdlDAi3zaXDoDio9OBfMgtRZ99l2IwVX3yc8=
  - secure: Gr3vUHQhRzQm8D0XRg+6TamimMAjlHHIU9OKF9alAdOcxxaexvyBqXsU89GYj7kXC3b9Z3+hyEU7VOpEDIvCv2cq0O83n4V8k7/A35NLidjsFkwd5Tp0oGkMYlsXcZTVYbEdGk3BzC/TVFmxas82fNFjwUG4qpmtjppPXlGxAsskwbEeqkos8hhghPfN/GJbyLytzpmOCcEOjpN0ks1KSdSPX94E5G0bgLdhF1mkaZUKmgp80qWTuX4oVgNcomPi72ybtOEutJLuMF6ClftjXMyRaGck+Ss8h9N7UfVJCn0HRuL9LObhCb3KwUWlJn97JpeF7NouUGWKcGpFCMzHRZ4HXyBakjJEBW6jb/3ufMXJCkiLjexLdnonCQ8Q52Tryyv7T+jMVUUtNv09Ulei76pIUnvfLE2QRxByiQsrKJvfTodsnyhhsHNgcORRCbg31AtlbL0j1vyAG1h+vGUo9qF9CsWEe63vDFDlFtTyCqIAi4THY+4YUA3k8JxGj2rjhhajIyUxwcoNLjEi9h9Uv1p9TBv4wBfRSiLLhUCkIaoXjse+UZW6V2qOiUCVTZOYtlgC2wymTSlifhf8tvHuyy+ssQ66lrfcBdaU+RvuxZeKUbcOvHgx1ZotF76NsoAxryRgpRaExIJLdKTrlDd9MPhBjHua3qs3ymcWqjsswq8=
  - secure: gQeYtOl5h1ThEZsXwqsgXN1WWS8xohLTcE/MoJ1ScWnl/Smq3z6BD+D8vntc6BMmjHWpu35WWKj1CWaGUaB0KuTa7G3FIvh6cA3g7/FTt/H2n8u37Si4megwyPBiGZAeQPMKFNUdtvfd/sD1/ee/zzZZdp+VJy7Od8ryasla5YlXZJ9VVn9qv7JdEW57n1mLn/6wo5U21GXEc6GHx05KdWNfyP3zXyJ2jaWshiaXrg/fRBmle9ULvfhlbxSvTJYzVV8QtPqjlsz+1tcATOhyzZgQjC0VdkLFgPP19KBf1OdXykNLcPqe0UV54hKcNwRI4DrrLSNck+YwZ2TpWeirPUtEJ8NSOVLTJ/wuUtAB1rsG4CrMVuF9Pgmr7H6Vh4neDjcS23twvf16XOwqPfk+4Cydnh+Olw82DGip/Q+dWJ8djDIp8OIoxX0wkNgLgf82RoZgsF01B9FKE5wFczl4c6q62RC3AOO4bauoWyr/SshmdTsKrPpxVJtuvjtIIZfJW+37pgehh8Z6wZs3BQaP/28kp0icvhuprDpEJFOsgltkWOSvwzdMTLZYMUeyo6V9aSS0F0Skbo9FE54D4i1JaefGlHyhoCY3RZAlfZ9IAuTlhJ9RI7asovlaJw7rWplNgjIhmJur7X9/cegsv0ww/tsUdq9VU7lvIz4177sEl7c=
  - secure: T3iAqb9k4FClN8ZEqDOy7FBGM1AVB+65qYKxMIB4A2cpgzVPNOCx/oQuKecjdXwT9tlrmDRz36vEY332uu1ZabB6+LRht3uhRCGh2szIW0YQ+yx1tfZv3q3YrGCw0MVIOOSc9wo37Q2B8eY3tlQrEX9e31AHP4IKrJW4Mm9AdaG+cpQ5hItxQsfahkUsyGPK9lVVdZ0iVLhSan4u+Yc+EBjQ/vFogebohXULQQf2Q4uNtg1bURteFFBcpQOwtv7HPIN74lAPA2kMChzk4oNyYvDh4hHwIgAgYeKrBXjIIf2Lbu8F6MngwM4j2XIhMzY/LXBFMBFnzKW8Hna6ClVIH4QeWmownpzHPLDQDIm59W7WkeaXUDbNoZMoEFXvpyK8hP7p2sughVhuoS3xdC2VGR5Syw53Y5m3fOkgxn0JUnqkRlfvexAvqtCK9l0+Rtf8+4me2Sta3GzRfbnSh0sFwKzdsyxuZ+QvMJfp3t4TxwNlcuiJ8+StKsCh7GMtcvV9xwTQ79Xf/pCkR3C8C5yS+udxZAAWb0JhaOfjUCtnp0ol5EPYOXUNqyWEpsTYnhBlRxs4ZdvuudTEIyyFyqIN1fkCi0s87I8oHDfZ8SXNlDRCaplXrzimlxw39K48KLfK4KTEAMKa8hhZYDNmyAFu2Q6RJ/t7H56HNzJXxydJehU=
